### ISSUE TITLE
Conda packages

### ISSUE THREAD

**Issue by anirbansen3027** [aws-samples/sagemaker-run-notebook#37]
Certain packages like prophet don't go well with pip install on sagemaker because of gcc issues where conda installation is the only option. 

<img width="1302" alt="Screenshot 2021-12-28 at 12 27 12 AM" src="https://user-images.githubusercontent.com/25762131/147499820-fb9613f3-1586-40a0-8fc1-71d3469e16f2.png">

But while installing through conda it throws an error probably because of the image not containing conda.
Any possible solution?

<img width="495" alt="Screenshot 2021-12-28 at 12 13 02 AM" src="https://user-images.githubusercontent.com/25762131/147498988-9cfe1703-4f02-45c7-b3ba-fc50826c46ee.png">

**Comment by tomfaulhaber** [comment]
Can you give me some more context here? Are you using the sagemaker-run-notebook package? If so, what container are you running with? How did you build it?

**Comment by anirbansen3027** [comment]
> Can you give me some more context here? Are you using the sagemaker-run-notebook package? If so, what container are you running with? How did you build it?

Yes I am using sagemaker-run-notebook and I am using the Python library

import sagemaker_run_notebook as run
job = run.invoke("test_prophet.ipynb",instance_type = 'ml.m4.4xlarge', extra_fns=[time_limit(86400)])
run.wait_for_complete(job)
run.download_notebook(job)

**Comment by tomfaulhaber** [comment]
The default execution container doesn't include conda, but is a simple environment with pip.

You can build your own container to run the notebook that includes prophet (and conda and gcc so you can get it built).

I was able to do this using the `continuumio/conda-ci-linux-64-python3.8` container as my base and adding an install.sh that installs prophet into the default environment. So install.sh would have:

```
sudo bash -c "PATH=/opt/conda/bin:$PATH conda install -c conda-forge prophet --yes"
sudo bash -c "PATH=/opt/conda/bin:$PATH pip install papermill jupyter nteract-scrapbook boto3 requests plotly"
```

Build the container using the `run-notebook` tool (you'll need to have permissions set for CodeBuild and ECR):

```
run-notebook create-container --base continuumio/conda-ci-linux-64-python3.8 --script install.sh prophet-runner
```

This creates the container image with prophet already installed. You should now be able to run it by adding `image="prophet-runner"` to your `run.invoke(...)` call.

Alternatively, you can run it from the command line with (for example):

```
run-notebook run --image prophet-runner ptest.ipynb
```

Doing this, I was able to successfully run a notebook with the Peyton Manning example included in the Prophet docs.

This way of building a container is a little hacky because (a) we're picking a random container that has conda and gcc in it as our base and (b) we need to reinstall a bunch of stuff to get the container to come out right. There may be a better base to build from out there.

A cleaner (but more complicated for you) way to do this would be to create a docker container "from scratch" with an OS base and add conda and the other components directly. To do this, you need to be able to run docker on your own machine and then you can run the instructions in the [DIY doc](https://github.com/aws-samples/sagemaker-run-notebook/blob/master/DIY.md#2-create-a-container-image-to-run-your-notebook).
